swagger: '2.0'
info:
  version: "0.0.1"
  title: <script>console.error(1);</script>
  description: <img src="x" onerror="alert(2)" />
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
